# Generated by Django 4.0.4 on 2022-05-26 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_remove_todo_todo_todo_decription_todo_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
