# Generated by Django 4.0.4 on 2022-05-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todo_created_date_todo_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='decription',
            new_name='description',
        ),
    ]
